import React,{useEffect,useState} from "react";
import Header from "./Header";
import indicator from "/public/img/indicator.png";
import Image from "next/image";
import katex from 'katex';
import 'katex/dist/katex.min.css';
import { getCookie } from "./checkcookie";
import { useRouter } from "next/router";

function Valuation() {
const router = useRouter();
  useEffect(() => {
    // Check the cookie and conditionally navigate to another page
    if (!getCookie()) {
      // The cookie is true, so navigate to the "home" page
      router.push("/"); // Update the path to your home page
    } else {
      // Use KaTeX to render the formula
      const ggmformula = "P_0 = \\frac{D_1}{r - g}";
      const ggmhtml = katex.renderToString(ggmformula, { displayMode: true });
      let formulaDiv = document.getElementById("ggmformula");
      formulaDiv.innerHTML = ggmhtml;

      const tsggmformula =
        "P_0 = \\frac{D_0 \\times (1 + g_1)}{r - g_1} + \\frac{D_n \\times (1 + g_2)}{(r - g_2) \\times (1 + r)^n}";
      const tsggmhtml = katex.renderToString(tsggmformula, {
        displayMode: true,
      });

      formulaDiv = document.getElementById("tsggmformula");
      formulaDiv.innerHTML = tsggmhtml;
    }
  }, [router]);

  return (
    <>
      <Header />
      <div className="content">
        
        <div className="Valuation">
          <h1>Valuation</h1>
          <div>
            <p>
              Valuation is a financial process that involves determining the
              intrinsic or market value of an asset, investment, company, or
              financial security. It is a crucial practice used in various
              fields, including finance, accounting, and investment, to assess
              the worth of an entity or an investment opportunity. The
              importance of valuation cannot be overstated, as it serves several
              vital purposes. Firstly, valuation helps individuals and
              organizations make informed financial decisions, such as buying or
              selling assets and making investment choices. Secondly, it plays a
              pivotal role in financial reporting and accounting by providing
              accurate figures for balance sheets and income statements.
              Additionally, valuation aids in assessing the financial health of
              a business, making it an indispensable tool for investors,
              creditors, and other stakeholders. Ultimately, valuation is the
              cornerstone of prudent financial management and prudent investment
              strategies, serving as a reliable means to assign a numerical
              value to assets and entities in a dynamic economic landscape.
            </p>
            <div className="topic">
              <h2>Methods of Valuation</h2>
              <p>
                Valuation is a multifaceted process with several methods
                employed to determine the worth of assets, businesses, or
                investments. The choice of valuation method depends on the
                nature of the asset or entity being assessed, the industry it
                belongs to, and the specific objectives of the valuation. Here
                are some commonly used methods of valuation:
              </p>
              <div className="subtopic">
                <h3>Discounted Cash Flow (DCF)</h3>
                <p>
                  DCF is a fundamental valuation method used to assess the
                  present value of future cash flows generated by an asset or
                  investment. Discounted Cash Flow (DCF) models are cornerstones
                  of financial valuation, providing a systematic approach to
                  estimate the intrinsic value of assets.
                </p>
              </div>
              <div className="subtopic">
                <h3>Market Capitalization</h3>
                <p>
                  This method is primarily used for publicly traded companies
                  and involves multiplying the current stock price by the total
                  number of outstanding shares. It provides a quick estimate of
                  the total value of a company based on the stock market's
                  assessment.
                </p>
              </div>
              <div className="subtopic">
                <h3>Comparable Company Analysis (CCA)</h3>
                <p>
                  CCA involves comparing the target asset or business to similar
                  companies in the same industry. By examining metrics like
                  price-to-earnings ratios or enterprise values, this method
                  provides a relative valuation based on industry benchmarks.
                </p>
              </div>
              <div className="subtopic">
                <h3>Comparable Transactions</h3>
                <p>
                  Similar to CCA, this method compares the target asset or
                  business to similar transactions that have occurred recently.
                  It is especially useful for valuing businesses in private
                  equity or mergers and acquisitions.
                </p>
              </div>
              <div className="subtopic">
                <h3>Earnings Multiplier</h3>
                <p>
                  Often used for small businesses, this method calculates the
                  value by applying a specific earnings multiple (such as
                  price-to-earnings or price-to-sales) to the company's earnings
                  or revenue.
                </p>
              </div>
              <div className="subtopic">
                <h3>Asset-Based Approach</h3>
                <p>
                  This approach calculates the value of an entity based on its
                  tangible and intangible assets. It considers the net asset
                  value, including property, equipment, patents, and
                  intellectual property.
                </p>
              </div>
            </div>
            <div className="topic">
              <h2>Discounted Cash Flow (DCF) Valuation</h2>
              <p>
                The Discounted Cash Flow (DCF) model is a fundamental and widely
                used method for valuing businesses and investment opportunities.
                At its core, the DCF model focuses on estimating the intrinsic
                value of a company by analyzing its future cash flows. The
                process involves two primary components. First, a pro forma
                analysis of future cash flows is conducted, which entails
                forecasting and projecting the cash flows a company is expected
                to generate over a specified period into the future. This phase
                necessitates meticulous examination of operating cash flows,
                capital expenditures, and changes in working capital. Second,
                the model entails discounting these projected cash flows back to
                their present value using a predetermined discount rate,
                typically the company's cost of capital. The result is a
                valuation that reflects the present worth of the company's
                anticipated future cash flows, considering the time value of
                money and the risk associated with those cash flows. This
                intrinsic value is pivotal for decision-making in areas such as
                investment, acquisitions, and assessing the attractiveness of
                potential business ventures, offering a comprehensive and
                analytical approach to ascertain the true worth of a company.
              </p>
              <div className="subtopic">
                <h3>Attributes</h3>
                <ul>
                  <li>Cashflow centric</li>
                  <li>Recognizes the time value of money</li>
                  <li>Versatile and customisable</li>
                  <li>Incorporates growth and risk</li>
                </ul>
              </div>
              <div className="subtopic">
                <h3>Inner Workings of the DCF</h3>
                <div>
                  <h4>Pro Forma Analysis of Future Cash Flows</h4>
                  <p>
                    This initial phase delves into the projection and estimation
                    of the future cash flows a company is poised to generate.
                    It's a meticulous undertaking, involving the forecasting of
                    operating cash flows, capital expenditures, and changes in
                    working capital. The end result is a detailed financial
                    projection that stretches across a defined period into the
                    future.
                  </p>
                </div>
                <div>
                  <h4>Discounting the Future Cash Flows</h4>
                  <p>
                    Once the projected cash flows are at hand, they undergo a
                    transformation. They are discounted back to their present
                    value, guided by a predefined discount rate, often
                    synonymous with the company's cost of capital. This process
                    is crucial, accounting for the time value of money and
                    acknowledging the risk inherent in those cash flows. The
                    outcome is an intrinsic value that, in essence, signifies
                    the present worth of the company's expected future cash
                    flows.
                  </p>
                </div>
              </div>
            </div>
            <div className="topic">
              <h2>Dividends Discount Model</h2>
              <p>
                The Dividend Discount Model (DDM) represents a specialized
                subset of valuation methodologies, primarily used for mature
                companies that have a consistent history of paying dividends to
                their shareholders. DDM is anchored in the concept that the
                intrinsic value of a company is determined by its expected
                dividend payments. The Gordon Growth Model, a prominent form of
                DDM, postulates a constant growth rate for dividends and
                formulates intrinsic value as a ratio of the most recent
                dividend payment, the required rate of return for equity
                investors (often representing the cost of capital), and the
                assumed constant growth rate of dividends. This simplicity makes
                DDM an appealing choice for companies with stable and
                predictable dividend policies, providing a direct means of
                evaluating their value. However, it is essential to recognize
                that not all companies pay dividends, especially younger and
                fast-growing firms. In such cases, the DCF model, which
                encompasses pro forma cash flow analysis and discounting, offers
                a more versatile approach to estimate intrinsic value and is
                better suited for a broader range of businesses, ensuring that
                valuation analyses can adapt to the diversity of corporate
                finance structures and practices.
              </p>
              <div className="subtopic">
                <h3>Attributes</h3>
                <ul>
                  <li>Dividends centric</li>
                  <li>Simplicity and easy to assess</li>
                  <li> Gives longterm investment perspective</li>
                  <li> Historical data reliance</li>
                </ul>
              </div>
              <div className="subtopic">
                <h3>Variations of the DDM</h3>
                <div>
                  <h4>Gordon Growth Model</h4>
                  <p>
                    DDM encompasses several variations, but the Gordon Growth
                    Model is perhaps the most well-known. It assumes a constant
                    growth rate for dividends, resulting in a concise formula
                    for intrinsic value.
                  </p>
                  <p>The Gordon Growth Model (GGM) formula is given by:</p>
                  <div id="ggmformula"></div>
                  <p>Where:</p>
                  <ul>
                    <li>
                      P0 is the current price or intrinsic value of the stock.
                    </li>
                    <li>D1 is the expected dividend in the next period.</li>
                    <li> r is the required rate of return (discount rate).</li>
                    <li> g is the constant growth rate of dividends.</li>
                  </ul>
                </div>
                <div>
                  <h4>Two-Stage Gordon Growth Model (Two-Stage GGM)</h4>
                  <p>
                    The Two-Stage GGM recognizes that a company's dividend
                    growth rate may not remain constant indefinitely. This model
                    is suitable for companies experiencing a period of high
                    growth followed by a more stable phase. It incorporates two
                    different growth rates: a high-growth phase (usually for a
                    limited number of years) and a stable-growth phase. The
                    formula for the Two-Stage GGM is as follows:
                  </p>
                  <div id="tsggmformula"></div>
                  <p>Where:</p>
                  <ul>
                    <li>
                      P0 is the current price or intrinsic value of the stock.
                    </li>
                    <li>D0 is the most recent dividend payment.</li>
                    <li>g1 is the high growth rate for the initial period.</li>
                    <li>
                      Dn is the dividend at the end of the high-growth phase.
                    </li>
                    <li>r is the required rate of return (discount rate).</li>
                    <li>g2 is the stable growth rate for the second period.</li>
                    <li>n is the duration of the high-growth phase.</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Valuation;
